WebProje/WebProje/Controllers/KayitOlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Models.EntityFramework;

namespace WebProje.Controllers
{
    public class KayitOlController : Controller
    {
        VeritabanıEntitiess db = new VeritabanıEntitiess();

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Kayit()
        {
            return View("Kayit",new KULLANICILAR());

        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Kayit(KULLANICILAR p1)
        {
            if (!ModelState.IsValid)
            {
                return View("Kayit");
            }
            var kontrol = db.KULLANICILAR.Where(x => x.KULLANICIEMAIL == p1.KULLANICIEMAIL).Count();
            if(kontrol == 0)
            {
                p1.KULLANICITIP = false;
                db.KULLANICILAR.Add(p1);
                db.SaveChanges();
                TempData["Success"] = "Uye Olma Islemi Basarılı!";
                return RedirectToAction("Login", "Security");

            }
            else
            {
                TempData["Crash"] = "Uye Olma Islemi Basarısız! Bu e-maile ait kullanici bulunuyor. ";
                return View("Kayit");
            }
            
        }
    }
}

WebProje/WebProje/Views/KayitOl/Kayit.cshtml
@model WebProje.Models.EntityFramework.KULLANICILAR
@{

    Layout = null;
}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<!DOCTYPE html>
<html>

<head>
    <title>Kayıt Ol</title>
    <link href="~/Content/css/stylelogin.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/Content/css/giris.css" />

</head>

<body>

    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <div class="brand_logo_container">
                        <img src="~/Content/images/logo.png" class="brand_logo" alt="Logo">
                    </div>
                </div>
                <div class="d-flex justify-content-center form_container">
                    @using (Html.BeginForm("Kayit", "KayitOl", FormMethod.Post))
                    {
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            @Html.TextBoxFor(m => m.KULLANICIEMAIL, new { @class = "form-control", placeholder = "e-mail" })
                            @Html.ValidationMessageFor(m => m.KULLANICIEMAIL)
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            @Html.TextBoxFor(m => m.KULLANICIAD, new { @class = "form-control", placeholder = "kullanici adi" })
                            @Html.ValidationMessageFor(m => m.KULLANICIAD)
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            @Html.TextBoxFor(m => m.KULLANICISIFRE, new { @class = "form-control", type="password",placeholder = "sifre" })
                            @Html.ValidationMessageFor(m => m.KULLANICISIFRE)
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <button type="submit" class="btn login_btn">KAYDOL</button>
                        </div>
                    }
                </div>

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Hesabın Var Mı Giriş Yap! <a href="/Security/Login" class="ml-2">Giriş</a>
                    </div>
                    <div class="d-flex justify-content-center links">

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

@{
    var message = TempData["Crash"];
}



<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>