WebProje/WebProje/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebProje.Models.EntityFramework;

namespace WebProje.Controllers
{
 
    public class SecurityController : Controller
    {

        VeritabanıEntitiess db = new VeritabanıEntitiess();
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(KULLANICILAR k)
        {
            var kullanici = db.KULLANICILAR.FirstOrDefault(x=>x.KULLANICIEMAIL == k.KULLANICIEMAIL && x.KULLANICISIFRE == k.KULLANICISIFRE);
            if (kullanici != null)
            {
                FormsAuthentication.SetAuthCookie(kullanici.KULLANICIEMAIL, false);
                Session["user"] = kullanici.KULLANICIID;
                Session["uyetip"] = kullanici.KULLANICITIP == true ? "Admin " : "Üye";
                Session["uyead"] = kullanici.KULLANICIAD;
                return RedirectToAction("Index","Home");
            }
            else
            {
                ViewBag.mesaj = "Geçersiz kullanıcı adı veya şifre girildi.";
                return View();
            }
            
        }
     
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

WebProje/WebProje/Views/Security/Login.cshtml
@model WebProje.Models.EntityFramework.KULLANICILAR
@{
    Layout = null;
}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>

<head>
    <title>Giriş Yap</title>
    <link href="~/Content/css/stylelogin.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/Content/css/giris.css" />

</head>

<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <div class="brand_logo_container">
                        <img src="~/Content/images/logo.png" class="brand_logo" alt="Logo">
                    </div>
                </div>
                <div class="d-flex justify-content-center form_container">
                    @using (Html.BeginForm("Login", "Security", FormMethod.Post))
                    {
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            @Html.TextBoxFor(m => m.KULLANICIEMAIL, new { @class = "form-control", placeholder = "e-mail" })

                        </div>
                        @Html.ValidationMessageFor(m => m.KULLANICIEMAIL)
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            @Html.TextBoxFor(m => m.KULLANICISIFRE, new { @class = "form-control", type = "password", placeholder = "sifre" })

                        </div>
                        @Html.ValidationMessageFor(m => m.KULLANICISIFRE)

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <button type="submit" class="btn login_btn">Giriş</button>
                        </div>
                        <div style="color:#ff0000">@ViewBag.mesaj</div>
                    }
                </div>

                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Kayıtlı Değil Misin? Kaydol! <a href="/KayitOl/Kayit" class="ml-2">Kaydol</a>
                    </div>
                    <div class="d-flex justify-content-center links">

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

@{
    var mesaj = TempData["Success"];
}
<script type="text/javascript">
    var mesaj = '@mesaj';
    if(mesaj)
        alert(mesaj);
</script>